### ISSUE TITLE
Argument feed, Counter tooltip does not reflect real numbers

### ISSUE THREAD

**Issue by mertturkmenoglu** [bbg/aristoteles#1]
# Steps to reproduce
* Go to the homepage.
* Hover over the total suggestion count.
* But However Because counts don't reflect the real counts.

Screenshot from the homepage:
<img width="477" alt="CleanShot 2022-08-03 at 8 36 15@2x" src="https://user-images.githubusercontent.com/34170799/182673162-c65e5542-af3e-45b6-81cd-59ebf0b92ddf.png">

Screenshot of the argument page:
<img width="2037" alt="CleanShot 2022-08-03 at 8 39 00@2x" src="https://user-images.githubusercontent.com/34170799/182673519-32d7b9eb-5e64-430b-aa0c-5cbc31fd8808.png">

**Comment by bbg** [comment]
@mertturkmenoglu Thank you for your feedback. Necessary development has been made for the error and this issue has been closed. You will be able to see the real counts after the deployment to be made soon.
